# Generated by Django 3.2.25 on 2026-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designorder',
            name='delivery_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='designorder',
            name='delivery_url',
            field=models.URLField(blank=True),
        ),
    ]
